services:
  db:
    image: mariadb:latest
    command: --max-allowed-packet=64MB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_USER: matomo
      MYSQL_PASSWORD: Password123
      MYSQL_DATABASE: matomo
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    ports:
      - 3306:3306
 
  app:
    image: matomo:latest
    restart: always
    environment:
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: Password123
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_HOST: db
      PHP_MEMORY_LIMIT: 2048M
    ports:
      - 8080:80
